# Student Placement Analysis
You are a data analyst working with a university's placement cell. They want to understand *what factors influence whether a student gets placed*, and use that insight to advise current students and design intervention programs for at-risk students.

You've been given a dataset of 100,000 student records containing academic performance, skills, extracurricular activity, lifestyle habits, and placement outcomes. Your job is to clean the data, explore it, and deliver actionable findings.

##  Part A: Data Loading & Cleaning (20 points)

In [3]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

### 1. Load the dataset and report its shape, column data types, and memory usage.

In [5]:
# Loading Dataset
student_df = pd.read_csv('student.csv')
student_df.head()

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa,Checking
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed,0.00,False
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed,0.00,False
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99,False
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed,0.00,False
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed,12.16,False

In [6]:
# Shape of the Data 
print("Shape :",student_df.shape)

Shape : (100000, 27)

In [7]:
# Column Datatypes 
print('Column Datatypes')
for i in student_df.columns: 
    print(f'{i} : {student_df[i].dtype}')

Column Datatypes
student_id : int64
age : int64
gender : object
cgpa : float64
branch : object
college_tier : object
internships_count : int64
projects_count : int64
certifications_count : int64
coding_skill_score : float64
aptitude_score : float64
communication_skill_score : float64
logical_reasoning_score : float64
hackathons_participated : int64
github_repos : int64
linkedin_connections : int64
mock_interview_score : float64
attendance_percentage : float64
backlogs : int64
extracurricular_score : float64
leadership_score : float64
volunteer_experience : object
sleep_hours : float64
study_hours_per_day : float64
placement_status : object
salary_package_lpa : float64
Checking : bool

In [8]:
# Memory Usage
student_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 27 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   student_id                 100000 non-null  int64
 1   age                        100000 non-null  int64
 2   gender                     100000 non-null  object
 3   cgpa                       100000 non-null  float64
 4   branch                     100000 non-null  object
 5   college_tier               100000 non-null  object
 6   internships_count          100000 non-null  int64
 7   projects_count             100000 non-null  int64
 8   certifications_count       100000 non-null  int64
 9   coding_skill_score         100000 non-null  float64
 10  aptitude_score             100000 non-null  float64
 11  communication_skill_score  100000 non-null  float64
 12  logical_reasoning_score    100000 non-null  float64
 13  hackathons_participated    100000 non-null  int64
 14  github_repos               100000 non-null  int64
 15  linkedin_connections       100000 non-null  int64
 16  mock_interview_score       100000 non-null  float64
 17  attendance_percentage      100000 non-null  float64
 18  backlogs                   100000 non-null  int64
 19  extracurricular_score      100000 non-null  float64
 20  leadership_score           100000 non-null  float64
 21  volunteer_experience       100000 non-null  object
 22  sleep_hours                100000 non-null  float64
 23  study_hours_per_day        100000 non-null  float64
 24  placement_status           100000 non-null  object
 25  salary_package_lpa         100000 non-null  float64
 26  Checking                   100000 non-null  bool
dtypes: bool(1), float64(12), int64(9), object(5)
memory usage: 19.9+ MB

### 2. Identify and report all columns containing missing or suspicious values (e.g., extracurricular_score has some 0 values that look like placeholders rather than genuine zeros — investigate and decide how to handle them, with justification).

In [10]:
# missing or suspicious values 
print("N/A Values:")
print(student_df.isna().sum())
print("\n\nNull Values:") 
student_df.isnull().sum()

N/A Values:
student_id                   0
age                          0
gender                       0
cgpa                         0
branch                       0
college_tier                 0
internships_count            0
projects_count               0
certifications_count         0
coding_skill_score           0
aptitude_score               0
communication_skill_score    0
logical_reasoning_score      0
hackathons_participated      0
github_repos                 0
linkedin_connections         0
mock_interview_score         0
attendance_percentage        0
backlogs                     0
extracurricular_score        0
leadership_score             0
volunteer_experience         0
sleep_hours                  0
study_hours_per_day          0
placement_status             0
salary_package_lpa           0
Checking                     0
dtype: int64


Null Values:

student_id                   0
age                          0
gender                       0
cgpa                         0
branch                       0
college_tier                 0
internships_count            0
projects_count               0
certifications_count         0
coding_skill_score           0
aptitude_score               0
communication_skill_score    0
logical_reasoning_score      0
hackathons_participated      0
github_repos                 0
linkedin_connections         0
mock_interview_score         0
attendance_percentage        0
backlogs                     0
extracurricular_score        0
leadership_score             0
volunteer_experience         0
sleep_hours                  0
study_hours_per_day          0
placement_status             0
salary_package_lpa           0
Checking                     0
dtype: int64

In [11]:
# Finding all vlaues where values is zero
(student_df.select_dtypes(include='number') == 0).sum()

student_id                       0
age                              0
cgpa                             0
internships_count            22203
projects_count                4948
certifications_count         13461
coding_skill_score               0
aptitude_score                   0
communication_skill_score        0
logical_reasoning_score          0
hackathons_participated      36722
github_repos                  1835
linkedin_connections             0
mock_interview_score             0
attendance_percentage            0
backlogs                     60884
extracurricular_score          131
leadership_score               266
sleep_hours                      0
study_hours_per_day              0
salary_package_lpa           45541
dtype: int64

In [12]:
# dropping extracurricular_score as in some fields, students have extracurricular activities but 0 extracurricular
student_df = student_df[student_df['extracurricular_score'] != 0]
student_df

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa,Checking
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed,0.00,False
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed,0.00,False
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99,False
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed,0.00,False
5,6,22,Male,7.44,CSE,Tier 2,1,5,1,49.758865,...,82.038139,0,54.150818,69.210022,No,9.1,3.4,Placed,11.78,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99995,99996,21,Male,7.97,Mechanical,Tier 2,0,3,5,71.483407,...,75.471631,0,54.399022,66.446410,Yes,8.0,4.3,Placed,14.54,False
99996,99997,18,Female,7.79,CSE,Tier 1,1,1,2,78.960574,...,77.286948,1,33.692154,69.025632,Yes,4.4,3.1,Not Placed,0.00,False
99997,99998,20,Female,6.71,IT,Tier 2,2,4,4,66.691775,...,93.115933,0,64.989215,32.733645,Yes,7.6,2.9,Placed,13.45,False
99998,99999,19,Female,7.21,CSE,Tier 2,2,3,0,67.214893,...,71.306355,1,72.478779,32.205517,No,4.9,2.8,Not Placed,0.00,False
99999,100000,22,Female,8.58,ECE,Tier 3,1,3,2,92.146277,...,89.919640,0,48.363818,21.166444,Yes,6.5,2.9,Placed,14.43,False

### 3. Check for and remove any duplicate student_id entries.

In [14]:
student_df['student_id'].duplicated().sum()

0

In [15]:
student_df = student_df.drop_duplicates(subset=['student_id'], keep='first') 
student_df.shape

(99869, 27)

### 4. Drop or fix the Checking column (a stray boolean column with no clear purpose) — document your reasoning either way.

In [17]:
# Dropping the column Checking as it does not have a clear purpose or meaning
student_df.drop('Checking', inplace=True, axis=1)
student_df.head()

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed,0.00
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed,0.00
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed,0.00
5,6,22,Male,7.44,CSE,Tier 2,1,5,1,49.758865,...,66.138578,82.038139,0,54.150818,69.210022,No,9.1,3.4,Placed,11.78

### 5. Convert placement_status into a numeric column placed_flag (1/0) for later correlation analysis.

In [19]:
# Converting Placement status to numeric columns
student_df['Placement Flag'] = student_df['placement_status'].map({'Placed':1,'Not Placed':0})
student_df[['placement_status', 'Placement Flag']].head(20)

   placement_status  Placement Flag
0        Not Placed               0
1        Not Placed               0
2            Placed               1
3        Not Placed               0
5            Placed               1
6        Not Placed               0
7        Not Placed               0
8            Placed               1
9            Placed               1
10       Not Placed               0
11           Placed               1
12           Placed               1
13       Not Placed               0
14           Placed               1
15           Placed               1
16           Placed               1
17       Not Placed               0
18           Placed               1
19           Placed               1
20           Placed               1

## Part B: Exploratory Analysis (25 points)

### 6. What percentage of students got placed overall?

In [22]:
# Percentage of people placed
print('Number of People placed:',student_df['Placement Flag'].mean()*100)

Number of People placed: 54.465349607986454

### 7. Compare average cgpa, coding_skill_score, and mock_interview_score between placed and non-placed students.

In [24]:
# Mean cgpa, coding skill and mock intervieew score between placed and not placed students
student_df[['cgpa','coding_skill_score','mock_interview_score','placement_status']].groupby('placement_status').mean()

                      cgpa  coding_skill_score  mock_interview_score
placement_status
Not Placed        7.483548           69.012159             69.388594
Placed            7.507932           70.510510             70.490309

### 8. Which branch has the highest placement rate? Which has the highest average salary_package_lpa?

In [26]:
# Branch wise highest placement rate
student_df[['branch','Placement Flag']].groupby('branch').mean()

            Placement Flag
branch
CSE               0.546409
Civil             0.552093
ECE               0.540911
EEE               0.543254
IT                0.543160
Mechanical        0.541099

In [27]:
student_df[student_df['Placement Flag']==1][['branch','salary_package_lpa']].groupby('branch').mean()

            salary_package_lpa
branch
CSE                  13.314609
Civil                13.304869
ECE                  13.311518
EEE                  13.318268
IT                   13.333013
Mechanical           13.313110

### 9. Is there a relationship between college_tier and placement rate? Build a table showing placement rate by tier.

In [29]:
student_df[['college_tier','Placement Flag']].groupby('college_tier').mean()

              Placement Flag
college_tier
Tier 1              0.545301
Tier 2              0.542820
Tier 3              0.547283

### 10. Do students with more backlogs have a noticeably lower placement rate?

In [31]:
student_df[['backlogs','Placement Flag']].groupby('backlogs').mean()

          Placement Flag
backlogs
0               0.572225
1               0.520345
2               0.448322
3               0.398279
4               0.353591
5               0.333333
6               0.000000

### 11. Use .corr() to build a correlation matrix of the numeric columns against placed_flag. Which 3 features correlate most strongly with placement?

In [92]:
numeric_df = (student_df.select_dtypes(include='number'))
print('Correlation between numeric columns')
corr_mat = numeric_df.corr()
corr_mat

Correlation between numeric columns

,student_id,age,cgpa,internships_count,projects_count,certifications_count,coding_skill_score,aptitude_score,communication_skill_score,logical_reasoning_score,...,backlogs,extracurricular_score,leadership_score,sleep_hours,study_hours_per_day,salary_package_lpa,Placement Flag,total_experience_score,well_rounded,at_risk
student_id,1.000000,-0.003801,-0.004233,-0.001618,0.000839,0.000425,0.004657,-0.000161,0.001642,-0.001660,...,0.000529,0.006140,0.002700,-0.001147,0.002621,-0.000693,-0.000647,-0.000482,0.001364,0.007416
age,-0.003801,1.000000,0.004111,0.003024,-0.002091,-0.000070,0.000637,-0.000812,-0.000388,0.000901,...,-0.001058,-0.001477,0.002643,-0.001815,-0.004193,0.000523,0.000738,0.000547,0.002327,0.002902
cgpa,-0.004233,0.004111,1.000000,0.004167,0.004106,-0.001266,0.004167,-0.003264,0.004461,-0.002479,...,-0.001167,-0.000195,0.000588,0.000378,-0.003547,0.076264,0.012230,0.003118,0.404141,0.004206
internships_count,-0.001618,0.003024,0.004167,1.000000,0.000564,-0.002572,-0.002787,0.000529,-0.001612,-0.000353,...,0.003493,-0.000280,0.000692,0.000686,-0.004017,0.114247,0.063527,0.446136,0.005551,0.000019
projects_count,0.000839,-0.002091,0.004106,0.000564,1.000000,0.001665,-0.003621,-0.000712,-0.002115,-0.005344,...,0.001946,0.003033,-0.007894,0.006182,0.000067,0.059109,0.060660,0.633259,-0.002229,-0.001618
certifications_count,0.000425,-0.000070,-0.001266,-0.002572,0.001665,1.000000,-0.001932,-0.000430,0.001726,-0.000411,...,0.002203,-0.000505,0.005305,-0.000507,-0.005296,-0.003486,-0.003835,0.517319,0.000507,-0.004145
coding_skill_score,0.004657,0.000637,0.004167,-0.002787,-0.003621,-0.001932,1.000000,-0.000581,-0.000059,0.002045,...,-0.003053,0.002448,0.004046,0.001541,0.004417,0.108334,0.050774,-0.003506,0.003755,-0.000462
aptitude_score,-0.000161,-0.000812,-0.003264,0.000529,-0.000712,-0.000430,-0.000581,1.000000,-0.002627,0.000415,...,0.001993,0.001519,-0.002342,0.006384,-0.002010,0.030893,0.031779,-0.000394,-0.001830,-0.003835
communication_skill_score,0.001642,-0.000388,0.004461,-0.001612,-0.002115,0.001726,-0.000059,-0.002627,1.000000,0.004042,...,-0.000531,0.003658,-0.002288,-0.001849,-0.001749,0.031754,0.032252,-0.001786,0.000286,0.002187
logical_reasoning_score,-0.001660,0.000901,-0.002479,-0.000353,-0.005344,-0.000411,0.002045,0.000415,0.004042,1.000000,...,-0.000719,0.000760,-0.002023,-0.003059,0.002608,0.035393,0.036342,-0.002285,0.000801,-0.000300
hackathons_participated,-0.001396,0.001519,-0.001881,0.000417,0.000944,0.001705,0.002818,0.000116,-0.001705,0.004013,...,0.000257,-0.003592,-0.001187,0.003799,-0.000740,0.000861,0.001360,0.365735,-0.005698,-0.003224
github_repos,-0.001850,-0.001960,-0.001733,0.000582,-0.000600,0.000142,-0.002777,-0.000907,0.003299,-0.001320,...,0.004056,-0.000400,-0.002068,0.001129,0.002821,0.005140,0.004847,0.001093,-0.000608,-0.002268
linkedin_connections,0.001633,-0.000480,-0.003923,-0.000709,-0.000973,-0.005133,0.001714,0.001799,-0.000370,-0.003324,...,-0.005436,0.002230,0.003272,-0.001947,-0.000083,0.003672,0.003279,-0.003385,-0.003700,-0.001447
mock_interview_score,0.002853,-0.004255,-0.000789,0.004479,-0.003066,0.003788,-0.005717,-0.003145,0.000505,0.004209,...,-0.003290,0.001812,0.007109,0.004776,0.001432,0.044749,0.045962,0.002770,0.003175,-0.005361
attendance_percentage,-0.004583,0.001416,-0.000438,0.000173,-0.002947,-0.000514,0.000758,-0.003036,0.001541,0.003969,...,0.002645,-0.002079,-0.002085,-0.000949,0.001651,-0.007875,-0.008522,-0.003058,-0.004647,-0.182407
backlogs,0.000529,-0.001058,-0.001167,0.003493,0.001946,0.002203,-0.003053,0.001993,-0.000531,-0.000719,...,1.000000,-0.003133,-0.001312,0.001966,-0.003185,-0.079795,-0.082100,0.004023,0.001393,0.261498
extracurricular_score,0.006140,-0.001477,-0.000195,-0.000280,0.003033,-0.000505,0.002448,0.001519,0.003658,0.000760,...,-0.003133,1.000000,0.001660,0.005027,0.005763,0.019866,0.019845,0.000223,-0.002143,-0.001317
leadership_score,0.002700,0.002643,0.000588,0.000692,-0.007894,0.005305,0.004046,-0.002342,-0.002288,-0.002023,...,-0.001312,0.001660,1.000000,-0.006419,0.005726,0.022064,0.022325,-0.002368,0.484052,0.000933
sleep_hours,-0.001147,-0.001815,0.000378,0.000686,0.006182,-0.000507,0.001541,0.006384,-0.001849,-0.003059,...,0.001966,0.005027,-0.006419,1.000000,0.006415,-0.004390,-0.004689,0.005333,-0.003020,-0.006619
study_hours_per_day,0.002621,-0.004193,-0.003547,-0.004017,0.000067,-0.005296,0.004417,-0.002010,-0.001749,0.002608,...,-0.003185,0.005763,0.005726,0.006415,1.000000,-0.001683,-0.001591,-0.004759,0.002784,-0.002527
salary_package_lpa,-0.000693,0.000523,0.076264,0.114247,0.059109,-0.003486,0.108334,0.030893,0.031754,0.035393,...,-0.079795,0.019866,0.022064,-0.004390,-0.001683,1.000000,0.984658,0.086921,0.040837,-0.018911
Placement Flag,-0.000647,0.000738,0.012230,0.063527,0.060660,-0.003835,0.050774,0.031779,0.032252,0.036342,...,-0.082100,0.019845,0.022325,-0.004689,-0.001591,0.984658,1.000000,0.065232,0.014167,-0.019666
total_experience_score,-0.000482,0.000547,0.003118,0.446136,0.633259,0.517319,-0.003506,-0.000394,-0.001786,-0.002285,...,0.004023,0.000223,-0.002368,0.005333,-0.004759,0.086921,0.065232,1.000000,-0.000739,-0.004330
well_rounded,0.001364,0.002327,0.404141,0.005551,-0.002229,0.000507,0.003755,-0.001830,0.000286,0.000801,...,0.001393,-0.002143,0.484052,-0.003020,0.002784,0.040837,0.014167,-0.000739,1.000000,0.001304
at_risk,0.007416,0.002902,0.004206,0.000019,-0.001618,-0.004145,-0.000462,-0.003835,0.002187,-0.000300,...,0.261498,-0.001317,0.000933,-0.006619,-0.002527,-0.018911,-0.019666,-0.004330,0.001304,1.000000

In [94]:
corr_mat_placed = corr_mat['Placement Flag'].drop('Placement Flag').sort_values(key=abs,ascending=False)
corr_mat_placed.round(4)

salary_package_lpa           0.9847
backlogs                    -0.0821
total_experience_score       0.0652
internships_count            0.0635
projects_count               0.0607
coding_skill_score           0.0508
mock_interview_score         0.0460
logical_reasoning_score      0.0363
communication_skill_score    0.0323
aptitude_score               0.0318
leadership_score             0.0223
extracurricular_score        0.0198
at_risk                     -0.0197
well_rounded                 0.0142
cgpa                         0.0122
attendance_percentage       -0.0085
github_repos                 0.0048
sleep_hours                 -0.0047
certifications_count        -0.0038
linkedin_connections         0.0033
study_hours_per_day         -0.0016
hackathons_participated      0.0014
age                          0.0007
student_id                  -0.0006
Name: Placement Flag, dtype: float64

## Part C: Feature Engineering (20 points)

### 12. Create a total_experience_score column combining internships_count, projects_count, certifications_count, and hackathons_participated (choose a weighting scheme and justify it).

In [36]:
student_df['total_experience_score'] = student_df[['internships_count','projects_count','certifications_count','hackathons_participated']].sum(axis=1)
student_df[['internships_count','projects_count','certifications_count','hackathons_participated','total_experience_score']].head(10)

,internships_count,projects_count,certifications_count,hackathons_participated,total_experience_score
0,4,6,1,4,15
1,1,3,6,0,10
2,0,1,1,0,2
3,0,2,2,1,5
5,1,5,1,3,10
6,0,2,2,0,4
7,3,4,2,2,11
8,2,5,0,0,7
9,2,2,2,0,6
10,2,4,4,2,12

### 13. Bin study_hours_per_day into Low / Medium / High categories using pd.cut(), and compare placement rates across bins.

In [38]:
student_df['study_quality'] = pd.cut(student_df['study_hours_per_day'],3,labels=['bad','medium','good']) 
student_df[['study_quality','study_hours_per_day']].head(10)

   study_quality  study_hours_per_day
0            bad                  3.6
1            bad                  2.3
2         medium                  5.9
3         medium                  4.4
5            bad                  3.4
6            bad                  3.1
7            bad                  1.6
8         medium                  4.2
9         medium                  4.5
10        medium                  4.0

### 14. Create a well_rounded flag: True if a student has leadership_score > 60, extracurricular_score > 60, AND cgpa > 7.5. What fraction of students qualify, and what's their placement rate compared to the rest?

In [40]:
# creating the well rounded column where 1 indicates True and 0 indicates False
student_df['well_rounded'] = np.where((student_df['leadership_score']>60) & (student_df['cgpa']>7.5),1,0)
student_df.head(20)

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa,Placement Flag,total_experience_score,study_quality,well_rounded
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,52.938240,Yes,6.7,3.6,Not Placed,0.00,0,15,bad,0
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,60.198856,No,4.4,2.3,Not Placed,0.00,0,10,bad,1
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,43.708803,No,8.8,5.9,Placed,11.99,1,2,medium,0
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,56.549154,Yes,8.1,4.4,Not Placed,0.00,0,5,medium,0
5,6,22,Male,7.44,CSE,Tier 2,1,5,1,49.758865,...,69.210022,No,9.1,3.4,Placed,11.78,1,10,bad,0
6,7,22,Male,7.54,CSE,Tier 3,0,2,2,68.816160,...,26.179746,No,8.9,3.1,Not Placed,0.00,0,4,bad,0
7,8,24,Female,6.86,Civil,Tier 3,3,4,2,87.471971,...,36.903695,Yes,8.8,1.6,Not Placed,0.00,0,11,bad,0
8,9,19,Male,8.52,Mechanical,Tier 2,2,5,0,100.000000,...,42.647145,No,8.5,4.2,Placed,16.33,1,7,medium,0
9,10,20,Female,8.07,Civil,Tier 2,2,2,2,93.421972,...,1.371853,No,5.9,4.5,Placed,16.17,1,6,medium,0
10,11,24,Male,6.09,IT,Tier 2,2,4,4,63.003171,...,47.419074,No,7.7,4.0,Not Placed,0.00,0,12,medium,0
11,12,20,Male,8.75,CSE,Tier 1,1,1,2,86.483537,...,81.287375,Yes,7.6,3.3,Placed,12.59,1,4,bad,1
12,13,20,Female,7.53,Civil,Tier 2,2,4,2,62.773295,...,38.981993,No,5.8,4.9,Placed,10.75,1,8,medium,0
13,14,22,Female,7.14,CSE,Tier 2,1,0,0,44.543725,...,41.088838,Yes,5.0,2.8,Not Placed,0.00,0,1,bad,0
14,15,21,Male,8.07,CSE,Tier 2,2,2,3,84.630973,...,0.969900,Yes,6.7,5.8,Placed,16.53,1,8,medium,0
15,16,20,Male,7.97,IT,Tier 2,2,1,0,81.127587,...,40.371437,No,6.5,2.3,Placed,14.67,1,4,bad,0
16,17,23,Male,7.97,CSE,Tier 1,0,6,1,65.559195,...,38.850062,No,6.6,5.7,Placed,12.74,1,9,medium,0
17,18,22,Male,8.54,Mechanical,Tier 1,0,4,3,65.908851,...,48.408011,No,9.3,3.1,Not Placed,0.00,0,9,bad,0
18,19,19,Female,7.06,CSE,Tier 1,3,2,4,84.905463,...,74.219999,No,8.4,3.4,Placed,13.26,1,10,bad,0
19,20,21,Female,7.65,IT,Tier 2,1,2,2,45.651202,...,49.075640,Yes,10.0,2.3,Placed,12.64,1,6,bad,0
20,21,23,Female,8.38,IT,Tier 1,0,2,3,66.831690,...,44.880400,No,9.0,3.1,Placed,11.69,1,6,bad,0

In [41]:
# The fraction of students who qualify for being well rounded students 
print('Percent of well rounded students:',student_df['well_rounded'].mean()*100)

Percent of well rounded students: 20.015219938118936

In [42]:
# Placement rate of students depending on their well rounded score
student_df[['well_rounded', 'Placement Flag']].groupby('well_rounded').mean()

              Placement Flag
well_rounded
0                   0.541124
1                   0.558757

### 15. Create an at_risk flag for students with backlogs >= 2 and attendance_percentage < 75. How many such students exist, and what's their placement rate?

In [44]:
# creating the at risk flag
student_df['at_risk'] = np.where((student_df['attendance_percentage'] < 74) & (student_df['backlogs'] >= 2),1,0)
student_df.head(20)

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa,Placement Flag,total_experience_score,study_quality,well_rounded,at_risk
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,Yes,6.7,3.6,Not Placed,0.00,0,15,bad,0,0
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,No,4.4,2.3,Not Placed,0.00,0,10,bad,1,0
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,No,8.8,5.9,Placed,11.99,1,2,medium,0,0
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,Yes,8.1,4.4,Not Placed,0.00,0,5,medium,0,0
5,6,22,Male,7.44,CSE,Tier 2,1,5,1,49.758865,...,No,9.1,3.4,Placed,11.78,1,10,bad,0,0
6,7,22,Male,7.54,CSE,Tier 3,0,2,2,68.816160,...,No,8.9,3.1,Not Placed,0.00,0,4,bad,0,0
7,8,24,Female,6.86,Civil,Tier 3,3,4,2,87.471971,...,Yes,8.8,1.6,Not Placed,0.00,0,11,bad,0,0
8,9,19,Male,8.52,Mechanical,Tier 2,2,5,0,100.000000,...,No,8.5,4.2,Placed,16.33,1,7,medium,0,0
9,10,20,Female,8.07,Civil,Tier 2,2,2,2,93.421972,...,No,5.9,4.5,Placed,16.17,1,6,medium,0,0
10,11,24,Male,6.09,IT,Tier 2,2,4,4,63.003171,...,No,7.7,4.0,Not Placed,0.00,0,12,medium,0,0
11,12,20,Male,8.75,CSE,Tier 1,1,1,2,86.483537,...,Yes,7.6,3.3,Placed,12.59,1,4,bad,1,0
12,13,20,Female,7.53,Civil,Tier 2,2,4,2,62.773295,...,No,5.8,4.9,Placed,10.75,1,8,medium,0,0
13,14,22,Female,7.14,CSE,Tier 2,1,0,0,44.543725,...,Yes,5.0,2.8,Not Placed,0.00,0,1,bad,0,0
14,15,21,Male,8.07,CSE,Tier 2,2,2,3,84.630973,...,Yes,6.7,5.8,Placed,16.53,1,8,medium,0,0
15,16,20,Male,7.97,IT,Tier 2,2,1,0,81.127587,...,No,6.5,2.3,Placed,14.67,1,4,bad,0,0
16,17,23,Male,7.97,CSE,Tier 1,0,6,1,65.559195,...,No,6.6,5.7,Placed,12.74,1,9,medium,0,0
17,18,22,Male,8.54,Mechanical,Tier 1,0,4,3,65.908851,...,No,9.3,3.1,Not Placed,0.00,0,9,bad,0,0
18,19,19,Female,7.06,CSE,Tier 1,3,2,4,84.905463,...,No,8.4,3.4,Placed,13.26,1,10,bad,0,0
19,20,21,Female,7.65,IT,Tier 2,1,2,2,45.651202,...,Yes,10.0,2.3,Placed,12.64,1,6,bad,0,0
20,21,23,Female,8.38,IT,Tier 1,0,2,3,66.831690,...,No,9.0,3.1,Placed,11.69,1,6,bad,0,0

In [45]:
# no of at risk students 
print('No of students at risk are:',student_df['at_risk'][student_df['at_risk'] == 1].sum())

No of students at risk are: 1176

In [46]:
# Placement rate of students depending on their risk score score
student_df[['at_risk', 'Placement Flag']].groupby('at_risk').mean()

         Placement Flag
at_risk
0              0.545723
1              0.454932

## Part D: Aggregation & Business Insight (20 points)

### 16. Build a .pivot_table() showing average salary_package_lpa with branch as rows and college_tier as columns.

In [49]:
pd.pivot_table(student_df,index='college_tier',values='salary_package_lpa',aggfunc='mean')

              salary_package_lpa
college_tier
Tier 1                  7.261919
Tier 2                  7.227397
Tier 3                  7.290403

### 17. Using .groupby() + .agg(), produce a single summary table per branch showing: student count, placement rate, average CGPA, and average salary — sorted by placement rate descending.

In [51]:
# branch wise total summary 
student_df.groupby('branch').agg({'student_id':'count', 'Placement Flag': 'mean', 'cgpa': 'mean', 'salary_package_lpa': 'mean'}).sort_values('Placement Flag', ascending=False)

            student_id  Placement Flag      cgpa  salary_package_lpa
branch
Civil            10011        0.552093  7.508289            7.345521
CSE              34778        0.546409  7.493276            7.275217
EEE              10161        0.543254  7.490708            7.235197
IT               19972        0.543160  7.500951            7.241965
Mechanical       10061        0.541099  7.482399            7.203714
ECE              14886        0.540911  7.505824            7.200345

### 18. Identify the *top 5%* of students by salary_package_lpa among placed students. What do they have in common (skills, branch, tier)?

In [53]:
top5 = student_df[student_df['Placement Flag'] == 1][student_df["salary_package_lpa"]>student_df["salary_package_lpa"].quantile(0.95)]
top5.head()

C:\Users\hajel\AppData\Local\Temp\ipykernel_26864\2065796470.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  top5 = student_df[student_df['Placement Flag'] == 1][student_df["salary_package_lpa"]>student_df["salary_package_lpa"].quantile(0.95)]

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa,Placement Flag,total_experience_score,study_quality,well_rounded,at_risk
8,9,19,Male,8.52,Mechanical,Tier 2,2,5,0,100.000000,...,No,8.5,4.2,Placed,16.33,1,7,medium,0,0
9,10,20,Female,8.07,Civil,Tier 2,2,2,2,93.421972,...,No,5.9,4.5,Placed,16.17,1,6,medium,0,0
14,15,21,Male,8.07,CSE,Tier 2,2,2,3,84.630973,...,Yes,6.7,5.8,Placed,16.53,1,8,medium,0,0
30,31,21,Male,7.28,CSE,Tier 1,0,4,3,80.564907,...,No,8.1,3.8,Placed,16.10,1,9,medium,0,0
31,32,18,Male,8.70,ECE,Tier 2,3,2,1,85.873104,...,Yes,3.8,4.3,Placed,16.04,1,7,medium,1,0

In [89]:
# common branch, skills and other parameters
top5[[ 'branch', 'college_tier','total_experience_score', 'sleep_hours', 'study_quality','extracurricular_score','salary_package_lpa']].value_counts(normalize=True).head()

branch  college_tier  total_experience_score  sleep_hours  study_quality  extracurricular_score  salary_package_lpa
CSE     Tier 1        3                       8.0          medium         42.908903              15.55                 0.000201
EEE     Tier 3        6                       6.3          bad            70.240476              16.56                 0.000201
                                              8.4          bad            31.689721              16.13                 0.000201
                                              7.9          medium         42.002422              18.57                 0.000201
                                              7.6          medium         46.670286              15.57                 0.000201
Name: proportion, dtype: float64